// DOM query selectors for various elements in the invoke.html template:

const invokeSelectors = {
    RpcDescription: '#rpcDescription',
    RpcUrl: '#rpcUrl',
    WalletDropdown: '.walletDropdown',
    CheckpointDropdown: '.checkpointDropdown',
    ContractsPlaceholder: '#contractsPlaceholder',
    ContractTemplate: '#contractTemplate',
    ContractName: '.contractName',
    Clickable: '.clickable',
    ContractDetail: '.contractDetail',
    MethodsPlaceholder: '.methodsPlaceholder',
    MethodTemplate: '#methodTemplate',
    MethodName: '.methodName',
    MethodDetail: '.methodDetail',
    InstructionsPlaceholder: '.instructions',
    ParametersInputArea: '.parametersInputArea',
    ParametersPlaceholder: '.parametersPlaceholder',
    ParameterTemplate: '#parameterTemplate',
    IntentSymbol: '.intentSymbol',
    IntentValue: '.intentValue',
    InvokeOnChainButton: '.invokeOnChainButton',
    InvokeOffChainButton: '.invokeOffChainButton',
    LaunchDebuggerButton: '.launchDebugger',
    InvocationResultPopup: '#invocationResultPopup',
    InvocationResultGasUsed: '#gas-used-value',
    InvocationResultVMState: '#vm-state-value',
    InvocationResultsPlaceholder: '#resultsPlaceholder',
    InvocationResultTemplate: '#resultTemplate',
    InvocationNoResultsTemplate: '#noResultsTemplate',
    ResultAsNumber: '.asNumber',
    ResultAsString: '.asString',
    ResultAsData: '.asData',
    ResultAsAddress: '.asAddress',
    CloseInvocationResult: '#closeInvocationResult',
    BroadcastResultPopup: '#broadcastResultPopup',
    BroadcastResultText: '#broadcastResultText',
    CloseBroadcastResult: '#closeBroadcastResult',
    InvocationErrorPopup: '#invocationErrorPopup',
    InvocationErrorText: '#invocationErrorText',
    CloseInvocationError: '#closeInvocationError',
    ParameterName: '.parameterName',
    ParameterInput: '.parameterInput',
    ParameterType: '.parameterType',
    InvokeInstructionsTemplate: '#invokeInstructions',
};

export { invokeSelectors };