// DOM query selectors for various elements in the invoke.html template:

const invokeSelectors = {
    JsonFileName: '#neoExpressJsonFileName',
    JsonFilePath: '#neoExpressJsonFullPath',
    RpcUrl: '#rpcUrl',
    WalletDropdown: '.walletDropdown',
    ContractsPlaceholder: '#contractsPlaceholder',
    ContractTemplate: '#contractTemplate',
    ContractName: '.contractName',
    Clickable: '.clickable',
    ContractDetail: '.contractDetail',
    MethodsPlaceholder: '.methodsPlaceholder',
    MethodTemplate: '#methodTemplate',
    MethodName: '.methodName',
    MethodDetail: '.methodDetail',
    InstructionsPlaceholder: '.instructions',
    ParametersInputArea: '.parametersInputArea',
    ParametersPlaceholder: '.parametersPlaceholder',
    ParameterTemplate: '#parameterTemplate',
    IntentSymbol: '.intentSymbol',
    IntentValue: '.intentValue',
    InvokeOnChainButton: '.invokeOnChainButton',
    InvokeOffChainButton: '.invokeOffChainButton',
    InvocationResultPopup: '#invocationResultPopup',
    InvocationResultText: '#invocationResultText',
    CloseInvocationResult: '#closeInvocationResult',
    InvocationErrorPopup: '#invocationErrorPopup',
    InvocationErrorText: '#invocationErrorText',
    CloseInvocationError: '#closeInvocationError',
    ParameterName: '.parameterName',
    ParameterInput: '.parameterInput',
    ParameterType: '.parameterType',
    InvokeInstructionsTemplate: '#invokeInstructions',
};

export { invokeSelectors };